/**
 * Todo app api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.pantasystem.todoandroidexample.api


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param title 
 * @param description 
 */

data class CreateTaskRequest (

    @field:JsonProperty("title")
    val title: kotlin.String,

    @field:JsonProperty("description")
    val description: kotlin.String? = null

)

