/**
 * Todo app api
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package net.pantasystem.todoandroidexample.api

import net.pantasystem.todoandroidexample.api.Account

import com.squareup.moshi.Json

/**
 * 
 *
 * @param token 
 * @param account 
 */

data class TokenWithAccount (

    @Json(name = "token")
    val token: kotlin.String,

    @Json(name = "account")
    val account: Account

)

