version: '3.6'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./:/usr/app/TodoBackend/
      - ../openapi/:/usr/app/openapi
    entrypoint:
      - sh
      - ./gradlew
      - bootRun
    restart: always
    depends_on:
      - psql
  psql:
    image: postgres:11-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: todo_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    